// constants.js
export const FETCH_EMAILS = 'FETCH_EMAILS'
export const FETCH_EMAIL_BY_ID = 'FETCH_EMAIL_BY_ID'
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS'
export const FETCH_EMAILS_FAILURE = 'FETCH_EMAILS_FAILURE'
